apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: udacitycapstone
  name: udacitycapstone
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udcaitycapstone
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: udcaitycapstone
    spec:
      containers:
      - image: chiphwang/udacitycapstone:latest
        imagePullPolicy: Always
        name: udcaitycapstone
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
