apiVersion: v1
kind: Service
metadata:
  labels:
    app: udacitycapstone
  name: udacitycapstone
  namespace: default
spec:
  clusterIP: 10.106.213.224
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30568
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: udcaitycapstone
  sessionAffinity: None
  type: NodePort
